# Generated by Django 3.1.4 on 2021-01-13 16:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articleapp', '0005_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='like_user_set',
            field=models.ManyToManyField(blank=True, related_name='like_user_set', through='articleapp.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
