# Generated by Django 3.1.4 on 2021-02-02 05:11

import articleapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0006_article_like_user_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='filename',
            field=models.CharField(max_length=64, null=True, verbose_name='첨부파일명'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=articleapp.models.get_file_path, verbose_name='첨부파일'),
        ),
    ]
